src/Site/UserBundle/Form/Type/OauthCreateFormType.php
<?php
namespace Site\UserBundle\Form\Type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
class OauthCreateFormType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder,array $options)
	{
	    $builder
	        ->add('username', null, array(
                'label' => '用户名:', 
                'attr' => array(
                    'placeholder' => '请输入用户名'
                )
            ))
            ->add('email', 'email', array(
                'label' => '电子邮箱:',
                'attr' => array(
                    'placeholder' => '请输入邮箱地址'
                )
            ))->add('plainPassword', 'repeated', array(
                'type' => 'password',
                'invalid_message' => '两次输入密码不一致',
                'required' => true,
                'first_options'  => array('label' => '密码:','attr' => array('placeholder' => '请输入密码')),
                'second_options' =>  array('label' => '确认密码:','attr' => array('placeholder' => '请重复密码')),
            ))->add('create', 'submit',array(
                'label' => '创建账户'
            ));	
	}
	public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'validation_groups' => array('SiteRegistration','Registration'),
        ));
    }
	public function getName()
    {
        return 'site_user_oauth_create';
    }
}

src/Site/UserBundle/Resources/views/Template/lesson/index.html.twig
<div class="user-content animated bounceInDown">
<div id="lessonlist">
{% set i = 0 %}
    {% set step = 3 %}
    {% if lessons|length == 0 %}
      {% set length = -1 %}
    {% elseif lessons|length % step  == 0 and lessons|length != 0 %}
      {% set length = lessons|length / step - 1 %}
    {% elseif lessons|length % step != 0 and lessons|length > step %}
      {% set length = lessons|length // step %}
    {% else %}
      {% set length = 0 %}
    {% endif %}
    {% if length == -1 %}
      <div>
          此分类还没有课程!
      </div>
    {% else %}
    {% for nails in 0..length %}
    <div class="row">
        {% set order = nails * step  %}
        {% for nail in order..order + step - 1 %}
            {% set i = 0 %}
                {% for lesson in lessons %}
                {% if nail == i %}
                    <div class="col-md-4 col-sm-4">
                      <a href="{{ path('site_lesson_show',{'index':lesson.index}) }}" class="thumbnail user-login lessons">
                        <img src="{{ image(lesson.image) }}" class="img-responsive" alt="">
                        <div class="caption">
                          <dl>
                            <dt><i class="icon-facetime-video"></i>{{ lesson.name }}</dt>
                          </dl>
                          <div class="tools">
                          </div>
                        </div>
                      </a> 
                    </div>
                {% endif %}
                {% set i = i+1 %}
            {% endfor %}
        {% endfor %}
    </div>
	  {% endfor %}
    {% endif %}
</div>
</div>